import type { Metadata } from 'next'
import Navbar from './Components/Navbar';
import { Poppins } from "next/font/google";
const pop = Poppins({ subsets: ['latin'],
  weight: ['400', '700'],
});
import './globals.css'
import Footer from './Components/Footer';
import { Toaster } from 'react-hot-toast';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head>
      <body className={`${pop.className} max-w-[1440px] mx-auto`}>
      <Navbar />
      <Toaster />
      {children}
     
      <Footer />
      </body>
    </html>
  )
}
